app:
    resource: "@AppBundle/Controller/"
    prefix:   /
    # type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

todo:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

todo_create:
    path:     /create
    defaults: { _controller: "AppBundle:Default:create" }
    methods:  { _method: post }

todo_update:
    pattern:  /{id}/update
    defaults: { _controller: "AppBundle:Default:update" }
    methods:  { _method: post|put }
    options:
        expose: true

todo_toggle:
    path:     /toggle
    defaults: { _controller: "AppBundle:Default:toggle" }

todo_delete:
    pattern:  /{id}/delete/{token}
    defaults: { _controller: "AppBundle:Default:delete" }
    methods: { _method: post|delete }

todo_clearcompleted:
    pattern:  /clearcompleted
    defaults: { _controller: "AppBundle:Default:clearcompleted" }
    methods: { _method: get }